### ISSUE TITLE
登陆认证回调里每次都调用微信获取token的接口，没问题吗？

### ISSUE THREAD

**Issue by vrecluse** [zhaoyao91/meteor-accounts-wechat-mp#1]
看到代码里登陆回调每次都会调用，这样不会导致老的token失效吗？正确的做法不是获取后保存复用，过7200秒再刷新么？而且微信限制了一天最多只能调用2000次，用户登录数量大的话很容易就被拒绝服务了吧

**Comment by zhaoyao91** [comment]
加我qq好么，我们讨论一下，754425108

**Comment by qintengfei** [comment]
确实是应该缓存一下用户的ticket和token,这样再开发微信jssdk时会方便很多

**Comment by devqin** [comment]
微信登录用的access_token 和 调用接口的access_token是不一样的东西，调用接口的access_token 才有限制2000
